name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: brach name
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '*'
          allowed_prefixes: 'ver/,issue/,doc/'
          ignore: master
          min_length: 5
          max_length: 1000
      - name: Commit changes
        run: |
          echo "test"
          git config --global user.name 'Aaron-Junker'
          git config --global user.email 'aaron.junker@edu.sh.ch'
          git commit -am "Push Docs"
          git push
